# Practical_6 = Numpy

# Exercise 1

Create a NumPy array of integers from 1 to 10.

In [1]:
import numpy as np
array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


# Exercise 2

In [ ]:
Create a 3x3 NumPy array filled with zeros

In [5]:
import numpy as np
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Exercise 3

In [ ]:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [6]:
evenly_spaced_numbers = np.linspace(0, 5, 10)
print(evenly_spaced_numbers)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


# Exercise 4

Create a 5x5 identity matrix using NumPy.

In [10]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Exercises 5

Create a 4x4 matrix with random values between 0 and 1

In [12]:
random_values = np.random.rand(4,4)
print(random_values)


[[0.72649215 0.49653217 0.43283712 0.254812  ]
 [0.34557969 0.67251812 0.17318949 0.15601929]
 [0.22508555 0.67933346 0.89025097 0.36181667]
 [0.33115244 0.96643821 0.3741356  0.1801666 ]]


# Exercise 6



Find the shape of a NumPy array.

In [14]:
a=np.array([1,3,4,3])
b=a.shape
print(b)

(4,)


In [16]:
a=np.array([[1,3,4,3],[1,2,5,6]])
c=a.shape
print(c)

(2, 4)


# Exercise 7

Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.



In [18]:
a=np.arange(1,17)
b=a.reshape(4, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# Exercises 8

Find the data type of the elements in a NumPy array

In [20]:
array=np.arange(1, 10)
array.dtype



dtype('int64')

# Exercise 9



Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [21]:
array=np.arange(1, 101)
dev=array[array % 2 ==0]
print(dev)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# Exercises 10



Generate a 6x6 matrix of random integers between 10 and 50.

In [23]:
array=np.random.randint(10, 50, size=(6, 6))
print(array)



[[11 17 45 14 34 35]
 [47 41 41 11 13 28]
 [48 18 33 10 36 37]
 [31 40 14 40 30 42]
 [14 23 22 23 29 41]
 [13 40 45 40 21 16]]


# Exercises 11



Slice a 2D NumPy array to extract a submatrix.

In [24]:
david=array[2:6, 1:6]
print(david)

[[18 33 10 36 37]
 [40 14 40 30 42]
 [23 22 23 29 41]
 [40 45 40 21 16]]


In [25]:
dev=david[1:4, 1:3]
print(dev)

[[14 40]
 [22 23]
 [45 40]]


# Exercise 12

Calculate the sum of all elements in a NumPy array.

In [32]:
all_sum=np.arange(1, 501)
np.sum(all_sum)


np.int64(125250)

# Exercise 13

Calculate the mean, median, and standard deviation of a NumPy array.

In [41]:
all_sum=np.arange(1, 501)
np.mean(all_sum)
np.median(all_sum)
np.std(all_sum)
print(np.mean(all_sum))
print(np.median(all_sum))
print(np.std(all_sum))


250.5
250.5
144.33727862198316


# Exercises 14

In [ ]:
Find the maximum and minimum values in a NumPy array

In [43]:
all_max_min=np.arange(1, 501)
np.max(all_max_min)
np.min(all_max_min)
print(np.max(all_max_min))
print(np.min(all_max_min))

500
1


# Exercises 15

In [ ]:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [57]:
ar_int=np.random.randint(10,20,size=20)
y=np.argmax(array)
y

np.int64(4)

# Exercise 16

Create a NumPy array and reverse its elements.

In [58]:
j=np.arange(15)
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
np.flip(j)

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Exercise 17

Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [60]:
t=np.random.randint(1,10,(3,3))
y=np.random.randint(11,20,(3,3))
t*y

array([[144,  66,  68],
       [ 39,  80,  55],
       [ 98, 152, 133]])

# Exercise 18

Perform matrix multiplication on two 2D NumPy arrays.

In [61]:
g=np.arange(12)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
np.diag(g)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

# Exercise 19

Perform matrix multiplication on two 2D NumPy arrays.

In [63]:
m1=np.random.randint(1,5,(2,2))
print(m1,"\t")
m2=np.random.randint(6,10,(2,2))
print(m2,"\t")
p=m1.dot(m2)
print(p)

[[4 2]
 [1 4]] 	
[[7 9]
 [6 9]] 	
[[40 54]
 [31 45]]


In [64]:
b=np.multiply(m1,m2)
b

array([[28, 18],
       [ 6, 36]])

# Exercise 20

Flatten a 2D NumPy array into a 1D array.

In [65]:
h=np.arange(12)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
b.flatten()

array([28, 18,  6, 36])

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---
